repository:
  has_wiki: false

# Labels: define labels for Issues and Pull Requests
labels:
  - name: "bug"
    color: c10000
  - name: ":nerd_face: 4geeks student"
    color: 7057ff
  - name: "enhancement"
    color: a2eeef
  - name: "first-timers-only"
    color: 69db89
  - name: "good first issue"
    color: 7057ff
  - name: "help wanted"
    color: 008672
  - name: ":star: P1"
    color: fbca04
  - name: ":star: P2"
    color: fbca04
  - name: ":vertical_traffic_light: Waiting QA"
    color: f1f1f1
  - name: ":memo: bc-writter"
    color: 98bde2
  - name: ":computer: bc-coder"
    color: 98bde2
  - name: ":beetle: bc-inspector"
    color: 98bde2
