name: Add Issue to Website Project (8_
on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    name: Add issue to Website Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.0
        with:
          project-url: https://github.com/orgs/breatheco-de/projects/8
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: website
          label-operator: AND
